### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by buzem** [shadigaafar/react-controlled-contenteditable#1]
`Error: Module not found: Can't resolve 'react-controlled-contenteditable'`

The component you created cannot be used

**Comment by shadigaafar** [comment]
Thank you for reporting the issue, I will check the problem. Please notice that it is still in the very experimental stage… and if you are planning to use it, make sure to update it to a new version every couple of days… it is still missing also some features, but everything will be finished soon.

**Comment by shadigaafar** [comment]
I could not find the same issue, could you give me more information? like, your react version and react-controlled-contenteteditable version. also, are you using typescript?

**Comment by shadigaafar** [comment]
Since no answer, I will have to close this issue.
