### ISSUE TITLE
Add demo page

### ISSUE THREAD

**Issue by yairEO** [shadigaafar/react-controlled-contenteditable#2]
I would like to see this package in action before I spend an hour time installing and configuring on my end

**Comment by shadigaafar** [comment]
I will soon.

**Comment by shadigaafar** [comment]
I have done a demo... link in README.

**Comment by crutchcorn** [comment]
Piggybacking off the only closed GitHub issue to say "THANK YOU" for writing this package. Super impressed with the work you've done here @shadigaafar

**Comment by shadigaafar** [comment]
@crutchcorn , Thank you for your encouragement. If you find any problems with it... Report it, so I can fix it right away.
