### ISSUE TITLE
README example unclear

### ISSUE THREAD

**Issue by yairEO** [shadigaafar/react-controlled-contenteditable#3]
If this is truly a controlled component, what is `html={content}`? 

The README does not explain anything.

A truly controlled component would have react JSX children and not the above

**Comment by shadigaafar** [comment]
When you use input and textarea, and you make it control, does it have JSX children ? No, controlled here means, the value of an input is controlled by react, and normally if you make an element contenteditable, and you controlled its value, it will not work as it supposed to be, cos caret position will lose its place. What I did, is make it controlled and restore the position of caret and adding some extra changes. Like navigating through nested format elements on arrow keys.

**Comment by yairEO** [comment]
Make sure to cover copy-pasting using mouse or keyboard, and sanitizing the pasted value so no script/css can be pasted.

I've done this in my own package, [Tagify](https://github.com/yairEO/tagify)

**Comment by shadigaafar** [comment]
Thanks for the reminder, I think now is kinda of ready, still did not sanitize it, but no problem with copy-pasting... there is still some problem when navigating using arrow keys with RTL languages, but I fix it.

**Comment by shadigaafar** [comment]
Could you please try it and give me your opinion? The link in the README.

**Comment by yairEO** [comment]
I will also check the source code for a deep analysis of the implementation
